name: Build Gosherve

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Gosherve
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Setup goreleaser
        run: |
          sudo snap install --classic goreleaser

      - name: Build gosherve
        id: build
        run: |
          goreleaser build --rm-dist --snapshot --debug

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: gosherve-dist
          if-no-files-found: error
          path: dist
